apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: test-deploy
    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - "1000000"